HAOS-Frigate-addon-Install-Notif-Backup
WARNING
This tutorial is in "To be validated" version and may not be usable as is! I will make a version 1 "validated" as soon as possible.
Introduction
There is extensive documentation for installing Frigate in an LSX Container, but I haven't found one for installing a Frigate add-on suite with Back-up and smartphone notification.

Having struggled and exchanged a lot on these topics, I think it's interesting to share what works for me with others.
This is actually a Version 0 of the documentation, as there are many points to improve. I will incorporate them as I modify my configuration.

Prerequisites
It is assumed that you have already:
installed Proxmox
installed HAOS
installed the following add-ons: HACS, Mosquitto browser, Alarmo (optional)
set up your external access: for my part with the DuckDNS and NGINX add-ons
tested your cameras with the rtsp or onvif protocol (or another but I haven't tested it)
configured a Telegram bot in HAOS.
Tutorial outline:
Connecting Coral in the HAOS VM
Installing the Frigate add-on
Frigate Configuration
Integration of Frigate (yes, it's different, I had trouble understanding this)
Downloading the "rclone backup" add-on which will be used to export photos and videos of people to Google Drive
Configuration of the "rclone backup" add-on
Building an Automation to restart the "Rclone backup" add-on whenever an event (detection) is generated by Frigate, to have recordings backed up to Google Drive fairly quickly (15 seconds) after the intrusion
Notification configuration using SgtBatten's blueprint
Creating an Automation to send photos and texts via Telegram_bot
Adding to Alarmo (or directly constructing by Automations) 2 actions related to alarms:
activation of camera detections if Alarm is armed (also used for testing)
deactivation of camera detections if Alarm is disarmed (also used for testing)
1. Connecting Coral in the HAOS VM
Initial proposal
There are multiple tutorials on "How to access Coral from Frigate", all based on integration from the USB port number.
Here I show you a method that is usually not used, because I preferred to do an integration from the name or ID of the Coral component, especially because I am not a Linux pro so I had difficulty in identifying the USB port, integrating it through the Proxmox interface, etc.
I have only included one photo because I think you must have already integrated USB dongles into your Home Assistant OS.

So, after connecting your Coral Key - with a USB cable and not directly to your computer (for my part a NUC), you need to:

go to the Proxmox interface,
click on your HAOS VM
go to the "Hardware" line
click at the top on "Add", then "Add USB device"
choose from the drop-down menu "Use USB device identifiers from device and manufacturer"
finally choose the device corresponding to Coral.
ATTENTION: you will need to do this manipulation twice because the Coral device changes its name.
the first time for me it was seen as GOOGLE manufacturer with an id
after some tests with Frigate it had disappeared from the config and so it had to be reinstalled, this time it had no manufacturer name it had to be identified with its id (which also changed)
after this second integration it is stable for me and recognized in Frigate (we will see later how to be sure of this).
More conventional proposal (found in various tutorials)
This is to integrate Coral from the USB port number .... successful manipulation for me by "breaking" the above method.
First, you need to identify the different USB dongles present on your "HA server" (for me a NUC).
For that in Proxmox:

go back to the level of the node where your HAOS VM is located,
select the shell of this node (for me I called it Proxmox)
run the lsusb command, which will give you the different ports used
Coral 1 lsusb

then go to the interface of the HAOS VM (for me VM 102 - VM Prod), and integrate Coral as above but this time by choosing "use USB port", which gives in detail:
go to the Proxmox interface,

click on your HAOS VM

go to the "Hardware" line

click at the top on "Add", then "Add USB device"

choose from the drop-down menu "Use USB port"

finally choose the device corresponding to Coral, by clicking on the correct line 'for me I chose line 2.6 while lsusb gave me usb 2 port 5 !!! I deduced it having identified all the other dongles/USB ports)
Coral 2 VM HAOS vision

!!! In both installation cases you can move on to the installation of Frigate, in the next §.
2. Installing the Frigate add-on
In your Home Assistant, go to Settings, Add-ons, Add-on Store, then click at the top right to add a new Add-on repository and add this link https://github.com/blakeblackshear/frigate to the list.

Restart Home Assistant

Go to Settings, Add-ons, Add-on Store (bottom for me), search for Frigate and click on Frigate, follow the instructions indicating that you are running it on HAOS.

Go back to Settings, Add-ons and check "Show in sidebar"

Frigate Add-on

From this moment you can configure Frigate.

3. Building the Frigate Configuration
Since you have Frigate in the sidebar (left for me), that's where we'll configure it.
For this, I am attaching my configuration file, it is called "Config Frigate addon oldchap56" and the comments are inside. For details on the content I recommend the excellent tutorial from which it is derived, written by Raynox and which you will find on YouTube

In summary, the chosen options allow each detection of a human by Frigate (made on the low-resolution stream) to take a snapshot and a video with the high-resolution stream.
These snapshots and videos are accessible:

either in the Frigate interface, by clicking on Events, we have all the detections classified chronologically,
or in the Media interface, classified by date then camera then again chronologically.
Similarly, to verify that Coral has been recognized by Frigate, you can:

click on Frigate in the left sidebar,
then go to the "System" tab,
and there you can check that Coral is working well !!
Frigate Interface to see Coral

4. Integration of Frigate
This integration allows the use of Frigate sensors, events etc. which communicate via mqtt with the rest of the world (HAOS, cameras etc.). This is what allows creating Automations from what happens inside Frigate.
For integration, you have to go to HACS (left sidebar), Integrations, click on Custom Repositories to include the following link in the Integration category
https://github.com/blakeblackshear/frigate-hass-integration.
Then, click on it to install. [TO BE VALIDATED]
Note: you can also integrate it directly from the blue button in the Github README.

5. Downloading the "rclone backup" add-on
It will be used to export photos and videos of people to google-drive as you go along.
Here again you will need to install the link in the repositories (Settings, Add-ons, Add-on Store, Three little dots at the top right, adding
https://github.com/jcwillox/hassio-rclone-backup)
Then restart HAOS, Add-on Store, Add Rclone back-up.
Note: you can also integrate it directly from the blue button in the Github README.

6. Configuration of the "rclone backup" add-on
My Rclone backup configuration is special, I had to "twist" the add-on a bit because it works by default as a backup at fixed times in advance (configured days, weeks, months, years in a cron).
My operation consists of restarting Rclone back up at each detection and not once a day.
The configuration is located in the Configuration part of the Rclone backup add-on (tabs at the top), my configuration (accessible in the file "Job for Rclone"). It allows launching the backup every time the add-on is started (The automation described in the following § will restart it).
Description of the job:

no mention of the time of the backup (erased line) to allow a backup every time the add-on is started
the command is copyto which copies new files from Frigate to Google drive each time it is launched (which allows me to manually manage the files in google drive - for example for destruction for example). If you want to automatically synchronize the source (HAOS) and the destination (Google Drive) which will always have the same content, put the rsynch command instead.
source: /media/frigate is where Frigate puts the files by default.
destination: google-drive:frigate. frigate is the directory at the root of my google drive where I do my backups.
WARNING: you have to configure access to Google drive by rclone !
To do this you need to get from Google Drive for Rclone a client id / client secret (which are created on its API for connecting applications): the complete procedure is on https://rclone.org/drive/#making-your-own-client-id

But, under HAos, I didn't manage to generate the token which is a third necessary information to connect an application to google drive. So I did (like Ryan72) an rclone installation under Linux (command line with the rclone config command) which worked right away, which allowed me to retrieve the token from the already obtained clientid/client secret.
I scrupulously copied the 3 pieces of information (client id, client secret, token) which allowed me to integrate them later in home assistant at the access configuration of Rclone in the config/rclone.conf file of your HAOS.
The example file is called "Rclone.conf"
If all this has worked well you will be able to see that you are connected by clicking on Rclone back-up in the left panel, in particular using the Explorer left menu and by "mounting" Google Drive. You should then see all your Gdrive directories in the table. This is proof that everything is well configured for Rclone back-up.

Re warning!
At the beginning we operate from Google in "test" mode for rclone. I suppose that the validity period of the token is very short in this mode. I asked for a token again and it worked right away .... TO BE CONTINUED.

7. Building an Automation to restart the "Rclone backup" add-on
This part seems the simplest to me, thanks to HAOS.
I just needed to build an Automation that uses a trigger "MQTT event" with the following information:

MQTT topic: frigate/snapshots/detected
and a condition that verifies that the payload is equal to "person"
and that's it !!
I am attaching my automation which is called "Job for restarting Rclone backup"

Conclusion
There are still many points to improve, but I hope this tutorial will help others.
It's still a Version 0, but it works pretty well for me.
